name: Execute Script Shell

on: [push]

jobs:
  Execute-Script:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repository
        uses: actions/checkout@v4

      - name: Execute Script
        run: |
          chmod +x ./scripts/script.sh
          bash ./scripts/script.sh